---
- hosts: all
  sudo: true
  vars:
    ip_address: 0.0.0.0
    hostname: AnsiblePBX
    system:
      download_dir: /usr/local/src
    pjproject:
      version: 2.3
    asterisk:
      version: 12.7.1
      install_samples: true
      freepbx_templates: true
      stun_server: stun.l.google.com:19302
      xmpp_user:
        username: asterisk
        password: password
        status: available
        message: It's Asterisk!
      manager:
        username: admin
        password: password
      extensions:
        - extension: 1060
          full_name: User A
          password: password
          username: 1060
          context: default
        - extension: 1061
          full_name: User B
          password: password
          username: 1061
          context: default
    ejabberd:
      manager:
        username: admin
        password: password
        role: admin
    freepbx:
      version: 12.0
  handlers:
    - name: reload apache
      service: name=httpd state=reloaded
    - name: reload asterisk
      service: name=asterisk state=reloaded
    - name: reload ejabberd
      service: name=ejabberd state=reloaded
    - name: start mysql
      service: name=mysqld state=started
  tasks:
    - include: tasks/dependencies.yml
    - include: tasks/apache.yml
    - include: tasks/pjproject.yml
    - include: tasks/asterisk.yml
    - include: tasks/ejabberd.yml
    - include: tasks/freepbx.yml
